language: objective-c
os: osx
osx_image: xcode11.6
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
cache:
  directories:
  - vendor/bundle

jobs:
  include:
    - stage: release
      env: Deployment
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - bundle exec rake package:release
      deploy:
        - provider: releases
          token:
            secure: m7YayvmctH5lyHj13EV2j898P5xfEfN/ZvFm2gL/xveTNOGaET1O4ZmGmHApxC2QwIZvtwmO3U9pmB4XVVQ7kIlTsl01h84y8gx1XQqEKoQINcaVaNCsh9EdxAqj08aiwe/1dp8W8rI/ptOrxzWJDWcxKx5tMIbBzctGeL3GDKphVvD44s43oosqQCKzP+qHiI6rRRxu+0QccdbTagwd0X/yaLZ0IbTo35hWFEyJ6NfJnmCW/lNwWj86YksLCZx0eKdxUSQlIhnm0upTyowudt9bv8vSdEYi2AtRKoana/X53593O8RAVEc+S6NgMmeQ1/ZD1eDeyYLzN/z21EHb4yiwTnMUUhDBMTn8KKTiiSVDQOfAyRwtKF+1qN2iDr9Dh3A8+dCxOxJJpIPImZimt8KMCKB9WTtnJhvIoMCDpc8l29XM/oBxjCiBFxPClb9CZ74T5b+xl+yIqy2u8RiaZ1Va5vmWjMSXDsGHoZ0rJTOBkBBhyr+47yIw2VeY2z2q5hiALV3DnE5Esxyddhw7OXNZcvKriujnxcTOJwphm4XBMI/3rSH27uz7AaNdUHfTwaKqimPR06Kdv65hKmFuA5p/GuRdSYfYASvXYYrPjqKkst1FP6sWjJtpXvZIT/06RXDbGXZ6LB3TFHpOahPy8ID746OyBKgWzOB3ZCNmFCk=
          file_glob: true
          file: build/release/*
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
    - stage: release
      env: Facebook_Utils
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - bundle exec rake test:facebook_utils:ios
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      env: Twitter_Utils
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - bundle exec rake test:twitter_utils:ios
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      env: ParseUI
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - bundle exec rake test:parseui:all
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      env: Cocoapods
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - bundle exec pod setup
        - travis_wait bundle exec pod lib lint --allow-warnings
      deploy:
        - provider: script
          skip_cleanup: true
          script: travis_wait bundle exec pod trunk push Parse.podspec --allow-warnings
          on:
            tags: true
            all_branches: true
    - stage: release
      env: Docs
      install:
        - bundle config set path 'vendor/bundle'
        - travis_wait bundle install
      script:
        - ./Scripts/jazzy.sh
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./docs/
          on:
            all_branches: true
            tags: true

